### ISSUE TITLE
"Unresolved reference: +" and "Unresolved reference: group"

### ISSUE THREAD

**Issue by copygirl** [DaemonicLabs/Voodoo#18]
I made a repo now: [HardcoreBytes @ addb827](https://github.com/copygirl/HardcoreBytes/tree/addb8276fa6d981c1a56635f3f5f9940d19603c1)

Command run:
```
./gradlew hardcorebytes_build
```

Full log: [voodoo.log](https://gist.github.com/copygirl/003a604f92164bb6ff9e019d0fc30d1e)
```
e: /home/copygirl/projects/minecraft/Hardcore Bytes/packs/hardcorebytes.voodoo.kts: (75, 5): Unresolved reference: group
ScriptDiagnostic(message=Unresolved reference: +, severity=ERROR, sourcePath=/home/copygirl/projects/minecraft/Hardcore Bytes/packs/hardcorebytes.voodoo.kts, location=Location(start=Position(line=82, col=9, absolutePos=null), end=null), exception=null)
e: /home/copygirl/projects/minecraft/Hardcore Bytes/packs/hardcorebytes.voodoo.kts: (82, 9): Unresolved reference: +
ScriptDiagnostic(message=Unresolved reference: +, severity=ERROR, sourcePath=/home/copygirl/projects/minecraft/Hardcore Bytes/packs/hardcorebytes.voodoo.kts, location=Location(start=Position(line=83, col=9, absolutePos=null), end=null), exception=null)
```

**Comment by NikkyAI** [comment]
move all the group blocks in `list { /*->here<-*/ }` and it will work
these are essentially just operators that change settings on all its children when they add them to the list they are declared in

in turn, they do not exist outside of that scope

usually i would recommend to use idea, but the highlighting is not really working all that well at the moment either because the plugin fails

**Comment by copygirl** [comment]
You know that I'm not a fan of IDEs. But thank you. This did fix my issue.
