### ISSUE TITLE
no builds of boostrap jar on jenkins ??

### ISSUE THREAD

**Issue by SDUBZ** [DaemonicLabs/Voodoo#23]
im trying to setup voodoo
but cant get the boostrap @NikkyAI 

any help would be much appreciated

**Comment by NikkyAI** [comment]
the bootstrap jar builds and publishes to maven.. the jenkins setup is a bit cursed.. the old setup of putting links on the project page on jenkins does not work anymore either..

and i am currently moving a lot of things in preparation for a version jump and major changes in voodoo frontend (what the modpack maker configures)
eg. moving from jenkins to github actions and moving to a bintray instead of the current maven

but this is going slowly because i am also very busy

maybe the best way to get started with voodoo right now is to look at existing projects and fork off them
https://github.com/copygirl/obsidian_fabric
and https://github.com/CitadelCore/DescentPacks

here is the bootstrap jars: http://maven.modmuss50.me/moe/nikky/voodoo/bootstrap-voodoo/

**Comment by SDUBZ** [comment]
oh thank youu 👍

**Comment by NikkyAI** [comment]
feel free to come into discord or irc for support as well

**Comment by SDUBZ** [comment]
oh thank you for the offer and irc does sound better ten discord once your always close to full servers limit :/
i do keep getting this issue tho  * What went wrong:
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings
err: Script compilation error:
err:
err:   Line 36:                 generateCurseforgeTexturepacks("TexturePack", "1.12", "1.12.1", "1.12.2")
err:                            ^ Unresolved reference: generateCurseforgeTexturepacks
err:
err: 1 error

**Comment by NikkyAI** [comment]
i think this was answered on irc already.. but.. i renamed the method and forgot to update the autogenerating project.. fixed that by now

if idea was able to load enough it should even show you which methods are available to you within the voodoo extension scope
but all of this is going away if i can make it anyways..

**Comment by SDUBZ** [comment]
oh okay cant wait to see the changes :)
